### ISSUE TITLE
Light Sector Portrayal - Sector Light Length

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#3] opened 2020-09-28 04:57 UTC
**S-101PT5 Action 18** - Discuss paper S-101PT5-15

[S-101PT5_15_EN_Light Sector Portrayal_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5289983/S-101PT5_15_EN_Light.Sector.Portrayal_V1.pdf)

**Comment by DavidGrant-NIWC** [comment] 2020-10-07 19:21
[S-101PT5_2020_15B_EN_NO_Light_sector_portrayal_discussion_points_S101PT5_V1.pdf](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/5343333/S-101PT5_2020_15B_EN_NO_Light_sector_portrayal_discussion_points_S101PT5_V1.pdf)

**Comment by alvarosanuy** [comment] 2020-10-08 04:48
**Row#2:** Preference is 25mm
**Row#4:** Although not ideal, HOs may not have access to this information and, if forced to add a range value, this would probably be encoded as UNKNOWN which won't help either. Our preference is to retain SLL. 
**Row#8:** Preference is VNR (If requested, mariners should be able to visualise the maximum range of lights. In this example, if the line length does not change, mariners may assume SLL is VNR).

In S-52 PL diagram for CSP LIGHTS 06, there are a couple of 'optional' display strategies for sector arcs that could be made mandatory and complement what we are trying to achieve here (particularly Note2).
![image](https://user-images.githubusercontent.com/70189016/95415102-25848000-097b-11eb-84d3-8a92b1bf07a8.png)
Would this be beneficial, and more importantly, possible to implement?
Could this work with SLL and VNR?

**Comment by DavidGrant-NIWC** [comment] 2020-10-08 14:17
> ![image](https://user-images.githubusercontent.com/62906211/95470185-7d58c200-094e-11eb-9695-f70ec85802cb.png)

The addition of an arc would be beneficial to resolve the below issue at the cost of some additional clutter. Would need direction on which arc(s) should be portrayed - both SLL and VNR, or just one?

> ![image](https://user-images.githubusercontent.com/62906211/95470580-f3f5bf80-094e-11eb-87f6-d76204219c92.png)

**Comment by forodd** [comment] 2020-10-09 07:21
I believe the placement of the arc is a fixed value in screen mm that stays the same regardless of zoom level. There is a possibility to override this in S-101 using the attribute sector extension:
![image](https://user-images.githubusercontent.com/32159177/95554633-ca9d6800-0a10-11eb-9f2b-7a451001da31.png)

**Comment by DavidGrant-NIWC** [comment] 2020-10-09 14:20
My understanding of the note is that the current portrayal would remain (fixed 25mm arc with optional sector extension) and an additional set of arcs would be displayed to show SLL and / or VNR (should have scaleMinimum to prevent clutter when zooming out).

**Comment by Christian-Shom** [comment] 2020-10-13 11:03
Due to the various issues and the needs for testings on examples, I'm not sure we can reach to an agreement during next VTC meeting. Suggest to agree on principles and set up a small group of volunnteers to elaborate a refined proposal.

- Agree with Alvaro's comments on rows 2, 4 and 8.

- Not sure guidance on "Sector extension" is clear in the DCEG: "calculated by ENC production software systems": HOW? More over, sector extension is in screen millimetres. This is surely in line with how the default sector arc is drawn, but shouldn't we adapt the arc so that it is also consistent with the sector line length (a bit like on a paper chart).

- I also recommend to make the various portrayal options mandatory so that all ECDISs behave in the same way.

**Comment by izzykim7** [comment] 2020-10-15 08:46
Row#7:if SLL>VNR then use VNR, SLL shouldnt be more than VNR according to S-101 DCEG

**Comment by forodd** [comment] 2020-10-15 09:02
Agree with Christian that we may not reach a final solution at the VTC now, some of the issues might require further testing in the testbeds. In that respect I hope we at least can agree on some kind of framework in the PC now for the portrayal of the attribute sector line length, then after further testing we may have a better position to adjust and finalize the values in the table.

We should also assume that the encoded value of SLL is always less than (or maybe equal to) VNR for each sector, maybe there is a need for a new validation check to ensure this in the encoding.

**Comment by LARRIVEEJCANADA** [comment] 2020-10-15 12:46
Good idea (more illustrations for understanding) we need to know if we have (HOs) to modify our S-57 coding practices upstream to be able to do this...  I am not sure I understand the implication of coding practices...

**Comment by DavidGrant-NIWC** [comment] 2020-10-16 17:41
(If reading in email - see issue on GitHub to ensure proper formatting)

# Background
(but also read the papers, especially with regard to obstructions):

| Term | Definition |
| :---: | --- |
|Sector Line<br>(leg line)|dashed line which delimits a sector arc|
|Sector Arc|A colored arc segment|
|Value of Nominal Range| The nominal range at which the light is visible (nautical miles)|
|Sector Line Length|Optional S-101 attribute which specifies the displayed (portrayed) length of the set of leg lines which delimit a sector arc (meters)<br>**Not present in S-57**|

### S-52 Sector Light Portrayal
|Full Sectors|Leg Lines|Portrayal (x0.5, x1.0)|Portrayal Notes|
|:---:|:---:|:---:|---|
|On|9 NM<br>(value of nominal range not encoded)|![image](https://user-images.githubusercontent.com/62906211/96288530-92b69780-0fb1-11eb-8141-aeabedd21749.png)<br>![image](https://user-images.githubusercontent.com/62906211/96288592-a82bc180-0fb1-11eb-9329-f600bdcb447e.png)|Portrayed length changes as user zooms in (longer) and out (shorter), but stays constant relative to geographic features. Indicates range of visibility.|
|Off|25mm<br>(per CSP)|![image](https://user-images.githubusercontent.com/62906211/96288445-70247e80-0fb1-11eb-8f62-c38a97da43e8.png)<br>![image](https://user-images.githubusercontent.com/62906211/96288312-3489b480-0fb1-11eb-9d05-2ee848f6f414.png)|Constant size, moves relative to geographic features as user zooms. Does not indicate range of visibility.|

### Issue Summary
The new sector line length attribute has been added to the S-101 data model, but it remains to update the drawing instructions generated by the Portrayal Catalogue in order to display the lines using the encoded value.

The paper proposes:
| Row # | valueOfNominalRange  | sectorLineLength  | Full sectors | Result |
|  :---: |  :---: | :---: | :---: | :---: |
| 1 | - | - | off | 25mm |
|2|-|-|on|?|
|3|-|sll|off|sll|
|4|-|sll|on|sll ?|
|5|vnr|-|off|25mm|
|6|vnr|-|on|vnr|
|7|vnr|sll|off|sll|
|8|vnr|sll|on|vnr?|

## Our opinion

1. To match S-52, whenever full sectors are off, sector arcs should be drawn at 25mm (+ any sector extension)
    - Result in rows 3 and 7 should be 25mm (+ any sector extension)

2. Per S-52 CSP, if _vnr_ is not encoded it defaults to 9 NM (S-52 PresLib 4.0.2 pg. 119 LIGHTS06)
    - Result in row 2 should be 9 NM
    - an encoding check is needed to require presence of _vnr_ when _sll_ > 9

3. S-101 DCEG 27.152 remark 2: "Sector lines must not extend beyond the nominal range of the light sector"
    - S-101 portrayal rule must use smaller of _vnr_ / _sll_ when both are present

Recommended length of portrayed sector legs based on above:
| Row # | valueOfNominalRange  | sectorLineLength  | Full sectors | Result |
|  :---: |  :---: | :---: | :---: | :---: |
| 1 | - | - | off | 25mm<br>(+ sector extension) |
|2|-|-|on|9 NM|
|3|-|sll|off|25mm<br>(+ sector extension)|
|4|-|sll|on|**sll**<br>(guaranteed <= 9 NM by encoding check)|
|5|vnr|-|off|25mm<br>(+ sector extension)|
|6|vnr|-|on|**vnr**|
|7|vnr|sll|off|25mm<br>(+ sector extension)|
|8|vnr|sll|on|**sll**<br>(portrayal rule uses smaller of **sll**, **vnr**)|

**Note**: our recommendation precludes portrayal of leg lines using _vnr_ when _sll_ is encoded, whereas the subject paper recommends using "Full Sectors" to switch between _vnr_ and _sll_. We feel using "Full Sectors" as proposed in the paper will be confusing to the mariner:
    - During dual-fuel operation.
    - If the display contains multiple sector lights (or even multiple sectors within a single light) and some of the sectors encode _sll_ but others do not.

We recommend opening a separate issue to discuss portrayal of the additional set(s) of sector arcs:
> My understanding of the note is that the current portrayal would remain (fixed 25mm arc with optional sector extension) and an additional set of arcs would be displayed to show SLL and / or VNR (should have scaleMinimum to prevent clutter when zooming out).

**Comment by forodd** [comment] 2020-10-20 09:02
Agree to discuss the arcs as a separate issue.

Agree that when sll is not populated, display should be the same as for S-52.(row 1,2,5,6)
sll attribute is not present in S-57 and hence will not be converted to S-101, it will need to be encoded by HOs in the S-101 dataset.
Since sll is an optional attribute, HOs may chose not to encode it for sectored lights where the default display is considered to be sufficient.

When an HO chooses to encode sll for a sectored light however, it is to override the default display of 25mm with the actual value to better indicate what danger this light sector is intended for, so this is the new default for this light sector. So row 7 should say sll.

For encoding, sll can never have a higher value than vnr. It makes no sense having a sector leg extending beyond the visible range of the light. This should be a new validation check, if sll is encoded larger than vnr it should report an error, and one of the values need to be changed to ensure sll<vnr.  A sector leg should never be drawn longer than vnr when vnr is populated.

Row 3 and 4 could be handled by an encoding rule (and validation check) mandating the encoding of vnr (>sll) when sll is encoded, or saying that sll can never be higher than 9 when vnr is not encoded?

I see a valid use case for wanting to extend the sector leg from sll to vnr, especially if the sll value is small compared to the vnr value and your ship is further away from the light than the sll range. Then you may want to extend the sector legs to check which sector your ship is within and which light (color and rhythm) to look for out the window. This option is not possible if the result in row 8 says sll, so I propose result in row 8 to be vnr.

In general I think we should not try to fix all the bad encoding in the portrayal, but rather look into adding validation checks to ensure the lights are properly encoded for display in the first place. 

And also if we cant reach final agreement on all the values in the table at this stage, at least the table and portrayal rules framework should be added to the PC to allow for further testing in the test beds by "tweaking" the xml files. Then we can more easily provide more examples and screen shots to reach out to a wider community for more feedback before finalizing the table values in the final version of the PC.

**Comment by DavidGrant-NIWC** [comment] 2020-10-21 15:09
Comparison of proposed portrayals.

The encoding was modified for illustrative purposes by adding a _sectorLineLength_ attribute to all **LightSectored** features. All red sectors have _sectorLineLength_ set to 10,000m, all yellow sectors have _sectorLineLength_ set to 5,000m.

| Sector | _sectorLineLength_ |
| :---: | :---: |
| Red | 10,000m |
| Yellow | 5,000m |

Extended sector arcs using dashed colored lines added to Norway and NIWC portrayals per S-52 LIGHTS06 Continuation Note 2.

**Click images to expand**
| Full Sectors | S-52 | Norway | NIWC |
| :---: | :---: | :---: | :---: |
|Off|![image](https://user-images.githubusercontent.com/62906211/96730495-34f4c780-1384-11eb-9ca2-6a7ea0b8e7ad.png)<br>25mm|![image](https://user-images.githubusercontent.com/62906211/96729174-ded35480-1382-11eb-9620-5ca1e81759e5.png)<br>_sectorLineLength_|![image](https://user-images.githubusercontent.com/62906211/96731718-8f425800-1385-11eb-8104-469cfa4b46df.png)<br>25mm|
|On|![image](https://user-images.githubusercontent.com/62906211/96730395-1bec1680-1384-11eb-81cc-64aa221119dd.png)<br>_valueOfNominalRange_|![image](https://user-images.githubusercontent.com/62906211/96729323-062a2180-1383-11eb-8d4d-9318089b8b8c.png)<br>_valueOfNominalRange_|![image](https://user-images.githubusercontent.com/62906211/96731385-31ae0b80-1385-11eb-9bc8-089b48073d8c.png)<br>_sectorLineLength_|

### Notes
Norway portrayal will only draw sector lines at 25mm if _sectorLineLength_ is not encoded.

NIWC portrayal will only draw sector lines to _valueOfNominalRange_ if _sectorLineLength_ is not encoded.

Either of these restrictions could be overcome by adding a third option to the _Full Sectors_ context parameter (_Off_, _On_, _Extended_), or by adding a new context parameter (_VNR Overrides SLL_), although we do not advocate either change.

The S-52 and NIWC portrayals do not show the light range when _Full Sectors_ is off - this supports decluttering the display. The Norway portrayal always shows the light range if _sectorLineLength_ is encoded. This is inconsistent with the S-52 portrayal and will be confusing in a dual-fuel environment.

**Comment by alvarosanuy** [comment] 2020-10-29 04:49
I combined all the proposed versions (so far) into one table:
![image](https://user-images.githubusercontent.com/70189016/97525976-40876480-19fc-11eb-9cc6-c2d066b7612d.png)

The AHO is of the opinion that SLL should only be allowed when VNR is populated (<> empty or Unknown). A validation check has been added to the table above.
Another validation cehck is recommended for options 7 and 8 to guarantee that, when SLL and VNR are populated, SLL is always equal or smaller than VNR.
With our proposal, the only difference (and we want some !) between S-52 and S-101 portrayal would be that when VNR and SLL are populated and mariners select 'Full sectors OFF'', S-101 ENCs will show sector legs according to SLL but S-57 ENCs will use 25mm instead.

**Comment by forodd** [comment] 2020-10-29 08:36
Thank you Alvaro for combining the proposals, it made it much clearer.
We mostly agree with AHO on all rows as it is, only difference is in row 3 and 4. 
But as we consider row 3 and 4 as invalid encoding(hence the validation check), we will not produce data containing these combinations, and hence it really doesn't matter for us what the result is. So we have no problems adjusting our proposal for these rows in line with the AHO proposal, that is 25mm for #3 and 9 NM for #4.

As stated earlier, the most important for us now is to have this added to the PC, allowing us to produce test data for Norwegian waters with real values for sll populated and having it portrayed in the testbeds, seeking mariners feedback, and then eventually consider adjustments for the final version of the PC later on based on that feedback.

**Comment by alvarosanuy** [comment] 2021-08-11 00:33
Thanks David
As per action **PortSG-05**, can you please provide Norway with a PC version where **SLL** behave according to the table I uploaded on 29/10? 
Norway has an action (**PortSG-06**) to test the proposed **SLL** behavior (using on-shore ECDIS) and report back to S101PT8 (December 2021). For testing purposes we should aim for sector arcs to follow **SLL** and always maintain the same relative position to the 'end of the line'.

I believe **sectorExtension**, as another independent attribute, does not make any sense because SLL and sector arcs have to behave as a unity and it shouldn't be possible, for example, to set **SLL** to be shorter than **arcExtension**. This would leave the sector arc 'floating' and not connected to **SLL** ...
There are parallel discussions about the purpose and usability of these 2 attributes at the DCEG subWG level so nothing is set in stone yet.

**Comment by DavidGrant-NIWC** [comment] 2021-08-20 22:21
Alvaro - could you notify interested parties via email (I'm not sure who watches this issue) that a PC supporting evaluation is now available (see below).

Someone will need to create test data to support the evaluation (the ESRI S-57 converter does not populate sectorLineLength). Otherwise, we could modify the prototype PC to set sLL from vnr to support evaluation (e.g. sLL = vnr / 2).

As an aside, while implementing this I noticed that sLL is an attribute of both sectorLimitOne and sectorLimitTwo, which means that in theory the sLL can be set to different values for the two limits. Perhaps it should be an attribute of sectorLimit?

In any case, a modified portrayal catalogue is available from the S-101 PC development repo on the "sector-line-length-proposal" branch:
[S-101 PC implementing sectorLineLength proposal](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/tree/sector-line-length-proposal)

---

Download by clicking the "Code" button and selecting "Download ZIP"
![image](https://user-images.githubusercontent.com/62906211/130297538-ec98889e-86c1-463f-8c9f-254e56047a9b.png)

---

Once downloaded, the test bed can be used to evaluate. The "Sector Line Length A/B" context parameter switches between AHO/Norway and NIWC proposed portrayals:
![image](https://user-images.githubusercontent.com/62906211/130298641-3efafc84-ba22-4797-8931-e3821219ca46.png)

**Comment by alvarosanuy** [comment] 2021-08-24 23:37
OFFICIAL
Morning Dave,

Thanks for making this available for testing. Last time I checked (and after my email a few months ago) the vast majority of the subWG members are now watching Github.
I have specifically included Odd in this email as NORWAY originally proposed this topic and they have been tasked to test and report findings/lessons learnt to the upcoming S101PT in early December.

Stay safe,

Alvaro

Alvaro Sanchez| Acting Director National Charting
Maritime Geospatial Branch | Australian Hydrographic Office
8 Station Street, Wollongong
T: +61 2 4223 6506 | M: +61 434 349 674

Defence Intelligence Group | Department of Defence
[AGO Logo2]

IMPORTANT: This email remains the property of the Department of Defence. Unauthorised communication and dealing with the information in the email may be a serious criminal offence. If you have received this email in error, you are requested to contact the sender and delete the email immediately.

**Comment by TomBovey** [comment] 2021-09-16 15:21
Dear all,
My colleague Tom Richardson informed me of the prototype portrayal catalogue exploring sector line length. To support this evaluation, please find attached some UKHO trial data for developmental testing. LightSectored Feature updated in position 50-46.66N., 01-05.65W
Best regards, Tom Bovey
UKHO Defence Standards

[101GB0050242G_sLL_testdata.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7178852/101GB0050242G_sLL_testdata.zip)

**Comment by DavidGrant-NIWC** [comment] 2021-11-02 13:50
As discussed at meeting:

|Full Sectors|SLL|S-52 Result|S-101 Result|
|:---:|:---:|:---:|:---:|
|False|No|25mm|25mm|
|False|Yes|25mm|SLL|
|True|No|VNR|VNR|
|True|Yes|VNR|VNR|

**Comment by forodd** [comment] 2021-11-03 10:59
For those interested, here is a link to a short video (in English) briefly explaining the use of sector lights in Norwegian waters. The video was made as part of a large ongoing NCA project to update all sector lights to be in line with international IALA standards.

https://www.kystverket.no/contentassets/2ddc4cf8817d44cd919e0dc955a5e43d/iala---main---eng---03---generell.mp4
  
More info about this project can be found on NCA's website:
https://kystverket.no/en/fairway/transition-to-iala-standard/

**Comment by Robert-Greer-iXblueDS** [comment] 2021-11-03 21:00
That was an interesting video. Thank you!

**Comment by forodd** [comment] 2021-11-04 13:48
I have now made a new version of the S-101 test dataset correcting the missing "minimumDisplayScale", thanks to Dave for pinpointing the error.


[101NO004R1010__.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7475221/101NO004R1010__.zip)

This dataset now imported fine into the SENC Editor, but then a second question arised, I am not able to locate it within the Shore ECDIS. Is there a way to jump to the location of a certain dataset or maybe edit the posititon of the own ship location ?

**Comment by forodd** [comment] 2021-11-04 17:36
Thanks Dave, found it now. Will continue to evaluate it and produce even more examples with different scenarios.

**Comment by alvarosanuy** [comment] 2021-12-01 22:51
**Decisions and Actions at 01DEC2021 (post 2nd meeting in November 2021):**

![image](https://user-images.githubusercontent.com/70189016/144326948-700439c4-ca2f-45f2-9bc3-ecf9a4a9b176.png)

**Comment by alvarosanuy** [comment] 2021-12-06 01:31
Refer to email trail:
[Email trail_30NOv21_06Dec21_Jeff,Odd,Dave,Alvaro.docx](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/7657281/Email.trail_30NOv21_06Dec21_Jeff.Odd.Dave.Alvaro.docx)

Dave, 

If we decide to retain 2 different line length (as per Norway’s request) I would say we will have to follow what they seem to do on paper charts which is adding the light sector arc at the end of the shortest of the sector arms.

In regards to Odd’s justification to retain different line lengths, I just want to mention that I do not think the use of different sector arc line lengths is explained that way in S-4. It may be a good use of the different sector line lengths but I’m not sure that, globally,  compilers or mariners relate the end of a sector arc line as an exit or entry point. Maybe something to run by the NCWG so this practice is discussed and potentially standardised. This way, S-4 guidance would be able to support Norway’s case.

**Comment by forodd** [comment] 2021-12-06 09:40
Thanks Alvaro for updating the issue.

Some more background on this topic.

We have received feedback from mariners (professional, Navy and others), for probably the last two decades, complaining about portrayal of sector lights in ECDIS in Norwegian waters, saying that portrayal of this is much better in Paper Charts and they want something similar in ECDIS. For many years we had to say (and got away with it) that S-57 was frozen and nothing we could do about it. Later years we had to say S-57 is still frozen, but it will be addressed and fixed in the future S-101 ENC. If we actually fail to fix it as promised, I am afraid mariners will lose their faith in ECDIS and will have no reason to upgrade to an S-100 ECDIS and rather seek to other (online) sources to get the information they really need. Similar to the way especially some smaller vessels not mandated to carry ECDIS do today, officially they are sailing on Paper charts, but the charts are just stored in a drawer while they in fact sail on different ECS systems fulfilling their needs. 

When it comes to the arcs, it should be no problem saying that the shortest of the two legs of a sector defines the very maximum for the arc extension. The drawing rules for the arcs need further work and testing. For narrow sectors it might make sense drawing the arc close to the end of the leg, while for wider (and long leg) sectors this will be very dominant in the chart, but this discussion belongs to another topic.

**Comment by forodd** [comment] 2022-05-31 10:15
We have now finally produced some more S-101 (FC 1.0.2) testdata for Sector Line Length. (2 cells).
This is converted from S-57 data using FC1.0.2 and the SLL values are added to inform in S-57 and picked up during conversion and populated to the appropriate SLL attributes in S-101. We do not have the tools for producing native S-101 data available yet. Will be able to do some editing of the cell after conversion though.

Unfortunately these converted datasets contain some errors (also Critical) that are not resolved yet. Not sure where the problem is, conversion tool is still under development, and we are working on it. Result is that I am able to load it in the S-100 viewer tool (v1.9.1.0) (see screenshot below), but it fails to import in the SENC Editor for now.

[S-101_SLL-Testdata_FC102.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8804165/S-101_SLL-Testdata_FC102.zip)
 
We will continue to improve the test data sets to reduce the number of errors, but will be happy to hear what is preventing it to load in the SENC editor, then we can try to adress those errors first.

![image](https://user-images.githubusercontent.com/32159177/171149680-4c76d17c-e040-4da3-a82a-acefd26baadd.png)

**Comment by DavidGrant-NIWC** [comment] 2022-06-01 15:56
It actually loads in the latest ShoreECDIS/SENC editor. It's likely the FC schema changes which cause the issue in the older version you are using.

The image below is with the current developmental PC, it doesn't have the SLL changes:

![image](https://user-images.githubusercontent.com/62906211/171447395-037144b0-5fa2-4e8a-af87-6d42ad09f94f.png)

**Comment by GuttormTomren** [comment] 2022-06-09 06:36
This has been a long process, with NCA/IALA presenting papers on requested improvements (from mariners) on a change in sector line length portrayal (similar to papercharts). This change was first accepted, then the technical implementation was discussed. There are different ways to solve this, discussion show several. The issues is still pending, but the latest proposal was not to include individual sector line length similar to paper charts.



Proposed solution:
 
![image](https://user-images.githubusercontent.com/93490864/172780748-5f9ce335-5a56-46b7-8275-04dc75c5d9cf.png)
 


Requested solution:
 
![image](https://user-images.githubusercontent.com/93490864/172780788-97068de2-7837-4f5f-bd30-78d766fd9caf.png)


IALA supports to have individual sector line lengths, as this is the preferred way of displaying sector lights in areas with numerous sector lights. This also highlights the intent of the aid (reference to point of danger). IALA will support further discussion on the subject, or will submit further documentation if required.

**Comment by forodd** [comment] 2022-06-24 09:02
After having had some offline talks with Guttorm and others we have resolved some misunderstandings and I will try to summarize it.
The addition of the Sector Line Length (SLL) attribute for sector lights, leads to 3 ways to draw the sector line legs (25mm, SLL, VNR), while the ECDIS GUI currently only allows for a selection between 2 (default and Full sectors). 

From S-52 13.2.4 (CSP LIGHTS06):
![image](https://user-images.githubusercontent.com/32159177/175501284-c12f6e27-6838-449d-a5cb-61a2b24661cc.png)

 
It seems well established among mariners that Full Sectors equals value of nominal range (VNR) and there are several use cases for the mariners need to extend sector legs to VNR on request. 

It seems most appropriate to keep it like this also for a dual fuel ECDIS, so that when full sectors are selected, they are consistently drawn to VNR length, regardless of the ENC in use being S-57 or S-101 and SLL populated or not. 
The 25mm is still the default drawing length, but when SLL is encoded, SLL will be the new default and mariner will still be able to extend to VNR on request.

This leads to these drawing instructions (Full sectors indicate the mariner’s selection, while SLL indicates whether the SLL attribute is encoded or not in the S-101 ENC).
 
![image](https://user-images.githubusercontent.com/32159177/175501350-3c107d1d-970f-48a6-9c63-60656f3cf3b8.png)


Notes.
•	Current data model has proven to be good, ability to encode different values for SLL1 and SLL2 is necessary, will be able to provide several examples and use cases to demonstrate this if needed.

•	The SLL attributes for sector lights are optional, no need for data producers to encode it unless they find it useful. Sector lights not having SLL encoded will display identical as for S-52.

•	Unit for the SLL attribute should be changed from meters to nautical miles to be in line with the unit for VNR, this has been captured as an action for edition 1.1.0 and will be discussed at the next meeting. Probably a straight forward issue.

•	It should be considered to extend the mariners selectable options in the ECDIS GUI to allow for the selection of the 25 mm legs even if the SLL is encoded if the mariner so wish. Something like default length is SLL when populated, otherwise 25mm, but mariner given the choice to select short sectors (25mm) in addition to the current only choice of Full sectors (VNR).
This will only be applicable for an S-100 ECDIS, not sure if such change will be possible to do for the dual fuel period (to avoid confusion vs native ECDIS systems) or will have to be postponed until after the dual fuel period. Guess this is more a political than a technical question.

•	Drawing of the sector arc (color band) is a different topic not covered by this issue but will need to be addressed as well.

•	Validation rules to ensure SLL values not exceed VNR value for each sector must be developed

**Comment by GuttormTomren** [comment] 2022-06-24 09:13
Veldig bra Odd!


Guttorm

Fra: Odd Aage Føre ***@***.***>
Sendt: fredag 24. juni 2022 11:02
Til: S-101-Portrayal-subWG/Working-Documents ***@***.***>
Kopi: Tomren, Guttorm ***@***.***>; Comment ***@***.***>
Emne: Re: [S-101-Portrayal-subWG/Working-Documents] Light Sector Portrayal - Sector Light Length (#3)


After having had some offline talks with Guttorm and others we have resolved some misunderstandings and I will try to summarize it.
The addition of the Sector Line Length (SLL) attribute for sector lights, leads to 3 ways to draw the sector line legs (25mm, SLL, VNR), while the ECDIS GUI currently only allows for a selection between 2 (default and Full sectors).

From S-52 13.2.4 (CSP LIGHTS06):
[image]<https://user-images.githubusercontent.com/32159177/175501284-c12f6e27-6838-449d-a5cb-61a2b24661cc.png>

It seems well established among mariners that Full Sectors equals value of nominal range (VNR) and there are several use cases for the mariners need to extend sector legs to VNR on request.

It seems most appropriate to keep it like this also for a dual fuel ECDIS, so that when full sectors are selected, they are consistently drawn to VNR length, regardless of the ENC in use being S-57 or S-101 and SLL populated or not.
The 25mm is still the default drawing length, but when SLL is encoded, SLL will be the new default and mariner will still be able to extend to VNR on request.

This leads to these drawing instructions (Full sectors indicate the mariner’s selection, while SLL indicates whether the SLL attribute is encoded or not in the S-101 ENC).

[image]<https://user-images.githubusercontent.com/32159177/175501350-3c107d1d-970f-48a6-9c63-60656f3cf3b8.png>

Notes.
• Current data model has proven to be good, ability to encode different values for SLL1 and SLL2 is necessary, will be able to provide several examples and use cases to demonstrate this if needed.

• The SLL attributes for sector lights are optional, no need for data producers to encode it unless they find it useful. Sector lights not having SLL encoded will display identical as for S-52.

• Unit for the SLL attribute should be changed from meters to nautical miles to be in line with the unit for VNR, this has been captured as an action for edition 1.1.0 and will be discussed at the next meeting. Probably a straight forward issue.

• It should be considered to extend the mariners selectable options in the ECDIS GUI to allow for the selection of the 25 mm legs even if the SLL is encoded if the mariner so wish. Something like default length is SLL when populated, otherwise 25mm, but mariner given the choice to select short sectors (25mm) in addition to the current only choice of Full sectors (VNR).
This will only be applicable for an S-100 ECDIS, not sure if such change will be possible to do for the dual fuel period (to avoid confusion vs native ECDIS systems) or will have to be postponed until after the dual fuel period. Guess this is more a political than a technical question.

• Drawing of the sector arc (color band) is a different topic not covered by this issue but will need to be addressed as well.

**Comment by GuttormTomren** [comment] 2022-06-24 09:51
Latest comment from Odd, all good, accepted by IALA/NCA.

**Comment by DavidGrant-NIWC** [comment] 2022-07-11 18:29
The remaining question for portrayal implementation: is the preference to add a 3-state context parameter, or to implement using the existing context parameter and the table above?

## Option A: Change Full sectors context parameter
S-100 v5 now allows enumerated values to be specified for context parameters. Change "Full Sectors" context parameter to allow selection between:
* Off (25mm)
* Truncated (SLL if present, VNR otherwise)
* On (VNR)

Advantage: Allows maximum flexibility
Drawback: May require mariner familiarization/training

## Option B: Don't change context parameter, use SLL instead instead of 25mm
![image](https://user-images.githubusercontent.com/62906211/178332254-bf02733e-0e72-402f-9105-40c014d08631.png)

Advantage: Familiar to mariner
Disadvantage: Might not be able to declutter the chart

**Comment by forodd** [comment] 2022-07-12 10:48
I would definitely prefer option A, if this will be allowed within the dual fuel frame work. A S-100/Dual Fuel ECDIS comes with many other improvements/new functionality probably requiring some kind of familiarization/training, this one should not be the hardest one to teach a mariner. Post dual fuel, Option A should be mandatory.

For option B clutter could end up being a problem , not controllable by the mariner, and we might end up with putting constraints on the data producer to reduce the use of SLL-attribute values (to avoid potential clutter) at the cost of not being able to utilize the full potential of the SLL-attribute for the support of safe navigation.

**Closed** 2022-07-13 01:27 UTC
Labels: Portrayal Update, Technical - Implementation

**Comment by alvarosanuy** [comment] 2022-07-13 01:35
**Decision made at Portrayal subWG meeting on 12/7/22**

1. Implement portrayal as per the following table:

![image](https://user-images.githubusercontent.com/70189016/178628846-d8481615-b05d-4c9a-a05b-1a8e40b74287.png)

**Comment by DavidGrant-NIWC** [comment] 2022-10-20 14:47
Implemented

#### Samples (click to expand)
|Dataset|Full Sectors Off|Full Sectors On|
|:---:|:---:|:---:|
|101NO004E1512__.000|![ShoreECDIS 2022-10-20T143131Z](https://user-images.githubusercontent.com/62906211/196980919-dc6a128f-57ac-4d73-96b5-815b8a0a10d6.png)|![ShoreECDIS 2022-10-20T143145Z](https://user-images.githubusercontent.com/62906211/196981027-5f713279-c8bd-4556-b76c-4864aedfd9d7.png)|
|101NO005X1310__.000|![ShoreECDIS 2022-10-20T142938Z](https://user-images.githubusercontent.com/62906211/196981483-8453b5bd-c438-4e8d-b125-44f6577fb337.png)|![ShoreECDIS 2022-10-20T142925Z](https://user-images.githubusercontent.com/62906211/196981535-9e5239e3-22cc-46cc-ac77-2fafa7db454a.png)|
