### ISSUE TITLE
Isolated danger symbol

### ISSUE THREAD

**Issue by Christian-Shom** [S-101-Portrayal-subWG/Working-Documents#96] opened 2022-07-27 12:38 UTC
From ENCWG "Display Sub WG"
Symbol ISODGR_01 is too big. 
![image](https://user-images.githubusercontent.com/71139640/181248189-d4007694-177c-4755-8cbe-c556bcf49315.png)
To be studied if the size of the symbol can be reconsidered.

**Comment by alvarosanuy** [comment] 2022-09-21 04:40
When compared with other obstruction symbols (see below) the isolated danger symbol size seems to be ok or, at least, consistent.

The problem in the screenshot above seems to be that the features are too close to each other at compilation scale. The 2 'isolated dangers' (if the same feature) could have been generalized into one area object and, the sounding to the NW, shouldn't have been selected. A different sounding (probably deeper), further away from the dangers, should have been selected instead to better complement the most significant charted features.

![image](https://user-images.githubusercontent.com/70189016/191414342-881a79c0-c8a4-4a12-95af-fd71074d5b39.png)


![image](https://user-images.githubusercontent.com/70189016/191414287-5176d1a3-5a63-4788-81e4-f85dc2f2d86c.png)

**Comment by DavidGrant-NIWC** [comment] 2022-09-21 15:05
![image](https://user-images.githubusercontent.com/62906211/191533555-d41f928d-411c-4ce1-93f9-2427794e5d75.png)

I don't know if the symbol is too big, but these can clutter the chart when SHOW_ISOLATED_DANGERS_IN_SHALLOW_WATERS is on (but only in areas which are particularly unsafe). I think this is mostly due to **UnderwaterAwashRock** features, which must be encoded as point features. The original screenshot has SHOW_ISOLATED_DANGERS_IN_SHALLOW_WATERS set to "On".

Per the DCEG:
> An area containing numerous dangers, through which navigation is not safe at the maximum display scale
> for the ENC data, should be encoded using an Obstruction feature of type surface, with attribute 
> category of obstruction = 6 (foul area).

So it may not be necessary to show these within a foul area. With viewing groups 24020 (Isolated underwater danger in unsafe water) and 31010 (data quality) turned off:
![image](https://user-images.githubusercontent.com/62906211/191537778-729033c8-0532-4dfb-9b96-153edb55fd8c.png)

The mariner does have the tools to address the clutter (toggle context parameter / viewing group(s)) but perhaps as Hugh has previously suggested the conditional symbology procedure could be re-assessed, maybe with some additional attribution on relevant features (add an inFoulArea attribute).

**Comment by alvarosanuy** [comment] 2023-01-13 00:30
**Portrayal subWG meeting - 12th January 2023**

1. The subWG concluded that the problem is not about portrayal if not about ENC compilation practices (e.g. attempt to use identical content in 'related' ENC and Paper Chart and expect uncluttered/readable display in both products;  ineffective use of SCAMIN, etc). 

2. The decision is to **Close this issue here** but also **refer it to the NCWG** for their analysis and assessment of the need for additional guidance in S-4 about things like: ENC first concept; key differences in portrayal between paper and ENC, the use of SCAMIN, etc. 

3. **Alvaro** to submit this issue for discussion at the next NCWG meeting in November 2023. This Issue will be closed.

**Closed as completed by alvarosanuy** 2023-01-13 00:30 UTC
Labels: Portrayal Update, NCWG
