### ISSUE TITLE
Wind Farm Area pattern element

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#68] opened 2022-03-30 00:13 UTC
P_5 point symbol generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx

2022-06-02: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_5_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8825937/P_5_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160726235-5445800c-e304-4e74-a546-e182b37c5f8d.png)
![image](https://user-images.githubusercontent.com/72803214/160726271-9e29041e-6aaf-4fa4-ad4d-83c720ee2472.png)

**Comment by IngaFjellanger** [comment] 2022-05-24 14:56
Offshore Production Area feature does not have any attribute or value which defines if wind farm is floating or fixed. The "category of offshore production area" attribute equal to 1 defines "wind farm". It does not specify a type of Floating or Fixed  wind motors. Hence we do not know which one of suggested symbols to select, WINDCON02 or WINDCON03. It does not make sense to create patterns with two different symbols. We suggest to use WINDCON02 (Fixed)

**Comment by SylviaSpohn-BSH** [comment] 2022-05-30 17:29
Why could the pattern symbol not be replaced by a wind rotor symbol in a cicle comparable to INT 1 L5.2; see #67

**Comment by MikusRL** [comment] 2022-06-02 17:06
I have updated .svg files in the .zip file in initial comment for NIWIC comment fix. 

Inga, good point. Will there be an addition to the DCEG to enable that portray? As I remember, there have been a discussion, that floating distinction is definitely needed, as fixed farms are just there where the physical structure is, where the navigation through a floating windfarm could be way more dangerous to the fact that in between the visible structures there chains/fastenings, which are of unknown height and/or breadth.

Sylvia, I think that is what is created - the INT 1 L5.2, but only without a circle. Group discussion: should I add the circle to the new symbols? These were created in the first place, because there were no windfarn symbols for S-57 without the position circle at the bottom.

**Comment by alvarosanuy** [comment] 2022-07-15 06:09
**Decision made at Portrayal subWG meeting on 13/7/22**

1. Mikus to create a new version of WIMCON02 that includes a circle with diameter of 9.94mm [as per SY(ENTRES51)].

Upload new files (SVG, CSS and Engineering Drawing) to this Github space.

2. Use LC(NAVARE51) for _Symbolised_ boundaries and S-52 instruction LS(DASH,2,CHGRD) for _Plain_ boundaries.

**Comment by MikusRL** [comment] 2022-08-28 21:52
I have created six symbols based on that symbol ENTRES itself is in three versions - 51, 61 and 71, and windfarms can be fixed or floating. 
[WNDFRM_Centered.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9440510/WNDFRM_Centered.zip)

I have not updated any of the .svg "metadata" entries, like with #28.

I also tried to analyze, if this symbol would need to be shifted by default, hapy to discuss. It might be a possibility that it fits in the DW symbol place, as these should never ocure at the same time to my understanding:
![187090085-cbfb2dbb-ca6b-4853-a5cb-370726bde5f3](https://user-images.githubusercontent.com/72803214/187095676-3905698f-e45a-496c-abf0-692ddce36c55.png)

![image](https://user-images.githubusercontent.com/72803214/187095752-3eaf9e9e-ef19-48c5-a57c-e7b01f81ffc0.png)

![image](https://user-images.githubusercontent.com/72803214/187095764-a0764fd2-3763-4d4c-9112-3dd847c29352.png)

![image](https://user-images.githubusercontent.com/72803214/187095776-b511bfa6-7a15-451b-a66b-383a83197e8a.png)

![image](https://user-images.githubusercontent.com/72803214/187095804-1f9c6f86-b739-41d0-b630-0d4ac1c86f98.png)

![image](https://user-images.githubusercontent.com/72803214/187095817-63a8b731-d0cb-4315-8f9b-46f9ed23fa08.png)

![image](https://user-images.githubusercontent.com/72803214/187095825-1d838372-09c4-4023-89ce-087c46d2f466.png)

**Comment by alvarosanuy** [comment] 2022-08-30 05:06
@MikusRL 

- WINDFRM52 is fine. It will be added to the **OffshoreProductionArea** rule when **categoryOfOffshoreProductionArea** = 1 (wind farm) rule and will include (as per S-52) a call to CSP RESTRN01 (and from that to RESCSP02).

- I believe all the other symbols are not required because:
         1. CSP RESTRN01 + RESCSP02 will 'add' new symbols (to be off set by the OEM) to an angle and distance from BOYMOR51 based on the values of the attribute **restriction** (if populated).
         2. **OffshoreProductionArea** feature does not have any attribute or value which defines if wind farm is floating or fixed. A modelling change has to proposed to the DCEG subWG first.

                     Does anyone have a different view on this???

**Comment by MikusRL** [comment] 2022-08-31 07:41
@alvarosanuy 

- I might be wrong here of course, but to my understanding, the symbols I created are the ones which should be called by that RESCSP02. And as I can figure it out, is that the same symbol, but with the small i or ! just aside them are enough to inform mariner to use the pick report, and no additional i symbol in the box or ! symbol in the circle is needed, as those might be needed actually, if RESARE is encoded on top of the ACHARE, and then there would be a doubling of same symbols. But, I would like to get a confirmation of course from someone who knows for sure from the group. Thanks. 
- Another thing about the floating wind turbines. I think that definitely there should be a possibility to encode them as floating too, both as individual features and as areas. As I can recall it all started in NCWG, where the paper symbol was considered a long time ago and it was recognized, that actually floating farms could be way more dangerous for navigating through them than the fixed ones, as chains, anchors, cables may be stretched at any direction from them, making the danger area around them much larger. One might say that RESARE or CTNARE then should be on top of that area too, but why to double encode and clutter the screen, when the same could be achieved with one object proper encoding. These were not added as symbols to INT1 then, as there were one or two places at that point in the world, where floating wind turbines were installed. There can be more by now. I have participated in IMarEST webinars, where engineering challenges have been discussed and analyzed on installed and on designs of them, so they definitely are and will be there. And again, I am happy of course to contribute in discussion, but not saying that it must be. May be Jeff could recall any of the DCEG discussions and decisions on this, so perhaps there are decisions I do not know about on these taken, and cases closed. I think that it is ok, if we have symbols ready, we can even register them as a group in GI registry, so they would be there to pick, if the need arises. Maybe other domains would be happy to use them straight away in their product specifications. (But that is of course not our groups main point and is a "long shot", I understand.

**Comment by alvarosanuy** [comment] 2022-09-01 04:07
> * I might be wrong here of course, but to my understanding, the symbols I created are the ones which should be called by that RESCSP02. And as I can figure it out, is that the same symbol, but with the small i or ! just aside them are enough to inform mariner to use the pick report, and no additional i symbol in the box or ! symbol in the circle is needed, as those might be needed actually, if RESARE is encoded on top of the ACHARE, and then there would be a doubling of same symbols. But, I would like to get a confirmation of course from someone who knows for sure from the group. Thanks.

Hi Mikus, the rule will put WINDFRM52 in the center of the Surface and will add additional existing symbology [shown in your screenshot from S-52 PresLib Ed 4.0(.2) - section 8.5.1 (Fig 4)] on a bearing and distance based on CSP RESCSP02. Refer to S-52 PresLib Ed 4.0(.2) Part I, Figure 27 (symbol acronyms inside blue bubbles).

@Mikan66 - NIWC to implement accordingly. This issue has been reopened until implemented by NIWC in PC 1.0.2.

**Comment by MikusRL** [comment] 2022-09-01 08:22
@alvarosanuy 
Yes, got it now. Thank you for the explanation and your time used to answer the question. I should have red the docs more careful initially. Thank you. 
And I trust you meant the reference to the latest S-52 PresLib - Ed 4.0(.3).

**Comment by mikan66** [comment] 2022-09-01 20:32
Is this the right approach for all of these?  A couple of samples here:  https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1234748868

**Comment by mikan66** [comment] 2022-09-02 16:58
Note that feature ProductionStorageArea still uses WNDFRM51.

**Comment by alvarosanuy** [comment] 2022-09-04 23:17
> Note that feature ProductionStorageArea still uses WNDFRM51.

@mikan66 - Noted. I do not see an issue with that. WNDFRM51 is used when  windfarms are on land.

**Comment by mikan66** [comment] 2022-09-06 11:30
See https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/114#issuecomment-1238024384

**Comment by alvarosanuy** [comment] 2022-09-07 00:21
Rule updated by NIWC - Close this issue.

**Closed as completed by alvarosanuy** 2022-09-07 00:21 UTC
Labels: New Portrayal, PC 1.0.2
