### ISSUE TITLE
Viewing group 21010 (incorrectly?) included in viewing group layer 3.1

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [S-101-Portrayal-subWG/Working-Documents#120] opened 2023-02-08 17:44 UTC
Unknown objects are symbolized using a question mark ![image](https://user-images.githubusercontent.com/62906211/217608323-844f9cf3-4667-4952-953c-961f6ab011ce.png) and are assigned to viewing group 21010. S-52 PL 4..0.3 14.3 assigns viewing group 21010 to viewing group layer 3.1.

This appears to be an error - currently unknown objects will toggle on/off with buoys, beacons, and structures. This may be OBE for S-101 depending on the outcome of https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/18#issuecomment-1422974300, but it should be brought to the attention of the ENCWG.

* [x] @alvarosanuy if you agree, please notify the ENCWG (by referencing this issue)

![image](https://user-images.githubusercontent.com/62906211/217608064-55704ad1-ea60-4750-a682-e9d84e010d0e.png)

**Comment by alvarosanuy** [comment] 2023-02-09 02:51
> [ ] @alvarosanuy if you agree, please notify the ENCWG (by referencing this issue)

Agree and will inform the ENCWG Chair.

Recommend leaving this issue open and monitor progress of Issue https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/18

I have allocated this issue the same labels than https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/18

**Comment by DavidGrant-NIWC** [comment] 2023-03-14 19:28
This and #123 are duplicates. Recommend closing this issue and leaving #123 open since it has an additional recommended action.

**Comment by alvarosanuy** [comment] 2023-03-14 22:58
Duplicate of https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/123

**Closed as completed by alvarosanuy** 2023-03-14 22:58 UTC
Labels: Technical - Implementation, PC 1.2.0 or later
