### ISSUE TITLE
Discoloured Water

### ISSUE THREAD

**Issue by MikusRL** [S-101-Portrayal-subWG/Working-Documents#61] opened 2022-03-29 18:35 UTC
P_1 point symbols generated from the spreadsheet: S-101_NewSymbology_organized by KHOA with additaional details_20220308.xlsx

**2022-06-02**: Updated .svg files fixing the positive y value to negative, symbolBox to match the svgBox (NIWIC comment fix):
[P_1_20220602.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/8825622/P_1_20220602.zip)

![image](https://user-images.githubusercontent.com/72803214/160744885-e3f5353a-b781-479a-8de5-9133e99d4693.png)
![image](https://user-images.githubusercontent.com/72803214/160744955-63e61103-0ea3-46ce-afd1-bcb22388ff76.png)
![image](https://user-images.githubusercontent.com/72803214/160745003-ec8fb8c8-3c0f-4136-a209-1c40e8afc0f1.png)

**Comment by SylviaSpohn-BSH** [comment] 2022-05-30 18:02
Suggest to reduce dot diametre in the outer circle comparable to OBSTN; don't use blue colour filling (blue is associated with depth ranges), perhaps a more common colour which is associated to the subject.

**Comment by MikusRL** [comment] 2022-06-02 16:09
I have updated .svg files in the .zip file in initial comment for NIWIC comment fix.

**Comment by alvarosanuy** [comment] 2022-07-06 05:03
I believe that **DiscolouredWater** warrants using blue infill colour to highlight the feature as 'possible danger' - stay away. 

Geometric primitive _Surface_ must replicate the portrayal proposed for _Point_ features (DSCWTR03).

In my opinion this feature should trigger an Indication (Update to A&I Catalogue).

**Comment by alvarosanuy** [comment] 2022-07-20 03:45
**Decision made at Portrayal subWG meeting on 14/7/22**

1. Implement as per S-52 for CTNARE (Point and Surface geometry) but using CHGRD colour instead.
2. **Mikus** - to create a new version of SY(CHINFO06) and SY(CTNARE51) using CHGRD. New files (SVG, CSS and Engineering Drawing) to uploaded to this Github space.
3. **Inga** - to create a new version of LC(CTNARE51) using CHGRD. New files (SVG, CSS and Engineering Drawing) to uploaded to this Github space.
4. A&I Catalogue - **DiscolouredWater** must trigger and Indication (yellow highlight).
5. DCEG subWG to discuss the need (use case) for geometric primitive Surface for this feature type.
6. If DCEG SubGroup decides to retain Surface, then an update to the FC and PC will follow as per current practices.

**Comment by MikusRL** [comment] 2022-07-20 10:53
> 2\. **Mikus** - to create a new version of SY(CHINF06) and SY(CTNARE51) using CHGRD. New files (SVG, CSS and Engineering Drawing) to uploaded to this Github space.

And I assume also the symbol SY(EMCTNAR1) needs to be created in CHGRD, as that is necesary for the complex linestyle, correct?

**Comment by alvarosanuy** [comment] 2022-07-20 22:53
> And I assume also the symbol SY(EMCTNAR1) needs to be created in CHGRD, as that is necesary for the complex linestyle, correct?

@MikusRL - Not sure what SY(EMCTNAR1) is. The idea is to display as per existing S-52 CTNARE instructions (see below) but using CHGRD colour versions of the listed symbols and lines.

![image](https://user-images.githubusercontent.com/70189016/180095577-d5c46a10-f07d-43b7-b986-f7b3b1eade9c.png)

**Comment by MikusRL** [comment] 2022-07-29 19:28
As per the discussions at the meeting on 12/7/22 regarding the discolored water encoding in accordance to the current UOC and for DCEG SubWG further discussions and consideration. As per the situation in July 2022 in PRIMAR RENC DB available ENC data searching on several variations of "Discolored Water" encoded in INFORM:

On CTNARE objects - 63 features in 38 ENCs (from 12 producers)
On OBSTRN objects - 42 features in 22 ENCs (from 10 producers)
On SEAARE object - 1 feature in 1 ENC (from 1 producer)
(the search uses strict search and not all possibilities might be found)

Disclaimer - this data is only indicative of the encoding practices, as does not include data from some HOs - either not members of the RENCs or distribution arrangements exclude the distribution through PRIMAR RENC.

Till info: @JeffWootton That is from the database of over 26 400 000 features and over 18 500 ENCs.

**Comment by LeoKuzmin** [comment] 2022-08-17 11:00
In according with:
"_3. Inga - to create a new version of LC(CTNARE51) using CHGRD. New files (SVG, CSS and Engineering Drawing) to uploaded to this Github space._"
Please, find the attached file with the SVG, xml, CSS & Engineering Drawing files of line style to depict Discoloured Water Area boundaries.
[DiscolouredWater_#61.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9358968/DiscolouredWater_.61.zip)

**Comment by MikusRL** [comment] 2022-08-29 11:19
Thank you Leo, much appreciated for creating the point symbol too. From your example I can see you have the center symbol too. Does it mean, that there is no need to create it separately out of CTNARE51, just to change the color, but it can change color of the symbol through area instruction? is that correct? Thanks.

**Comment by LeoKuzmin** [comment] 2022-08-29 11:40
Hi Micus,
I created a new symbol DSCWTR51 to draw gray central symbol in other place relatively position of CTNARE51. In practice there are many cases where central symbols of Discolored Water area and Caution Area should be drawn in the one place. We should move these symbols apart. If you need I can upload necessary file here 
![image](https://user-images.githubusercontent.com/106175259/187200760-0f9c0c2c-ff63-4b75-a2e0-11a24bb04192.png)
[DiscolouredWater_#61.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9444865/DiscolouredWater_.61.zip)

**Comment by alvarosanuy** [comment] 2022-09-01 05:38
@Mikan66 - Implement as follows:

- Point - Use new symbol EMDSCWTR.svg
- Surface symbolised boundaries - New complex line DSCWTR51.xml + new central symbol DSCWTR51.svg
- Surface plain boundaries - Dashed line [LS(DASH,2,CHGRD)] + new central symbol DSCWTR51.svg

@LeoKuzmin - DSCWTR51.xml refers to a symbol (dash with triangle in CHGRD colour) called 
EMAREGR1. Should this symbol be provided to NIWC (and registered in the IHO registry)??? I couldn't find it in any of the ZIP files provided in this issue.

**I have reopened this issue and I will leave it open until changes are implemented in PC 1.0.2 by NIWC.**

**Comment by LeoKuzmin** [comment] 2022-09-01 09:08
The symbol EMAREGR1 is supported by the current PC, please, see here: 
[https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/EMAREGR1.svg](url)

**Comment by alvarosanuy** [comment] 2022-09-01 22:53
> The symbol EMAREGR1 is supported by the current PC, please, see here: [https://github.com/iho-ohi/S-101_Portrayal-Catalogue/blob/main/PortrayalCatalog/Symbols/EMAREGR1.svg](url)

Thanks for the clarification. No further action then.

**Comment by mikan66** [comment] 2022-09-13 14:21
I don't have proper test feature for display, but here is representative using Offshore Platform.
Surface and Plain Boundaries = false
![image](https://user-images.githubusercontent.com/4913543/189925872-e29e2009-4a5f-4268-89ce-1055e5d993c7.png)

Surface and Plain Boundaries = true
![image](https://user-images.githubusercontent.com/4913543/189926178-b463b0f0-16d1-41dc-b53c-36d78d955444.png)

Point Feature:
![image](https://user-images.githubusercontent.com/4913543/189926365-f736b56f-21f5-439a-9baf-e605d5a9d604.png)

See commit: https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/40#issuecomment-1245507312

**Comment by alvarosanuy** [comment] 2022-09-13 23:46
@mikan66 - The surfaces (Plain and symbolised) should show the new central symbol DSCWTR51.svg (in CHGRF colour) but the only thing I can see is a similar symbol but in magenta (?). I looked at the *.lua file and the instructions seem to be ok though .......
Can you please double check implementation?

**Comment by mikan66** [comment] 2022-09-14 09:16
> @mikan66 - The surfaces (Plain and symbolised) should show the new central symbol DSCWTR51.svg (in CHGRF colour) but the only thing I can see is a similar symbol but in magenta (?). I looked at the *.lua file and the instructions seem to be ok though ....... Can you please double check implementation?

Linestyle color in rule is wrong based on this comment, but I'm a bit confused which color is desired here for line and symbol?

 Looking at symbol SVG it has CHGRD defined as color.  It appears as: 
![image](https://user-images.githubusercontent.com/4913543/190113621-a376df3e-c4a6-46d5-81e5-04f543e710cb.png)

Replacing color in SVG file to CHGRF yields this slightly different shade: 
![image](https://user-images.githubusercontent.com/4913543/190114069-8cd3850a-4ec1-451d-b3c7-55e0739a072e.png)

**Comment by alvarosanuy** [comment] 2022-09-15 05:38
> Linestyle color in rule is wrong based on this comment, but I'm a bit confused which color is desired here for line and symbol?

@mikan66 - Refer to my last comment (15/9/22) in Issue https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/65

**Comment by kusala9** [comment] 2022-09-19 14:39
> I don't have proper test feature for display, but here is representative using Offshore Platform. Surface and Plain Boundaries = false ![image](https://user-images.githubusercontent.com/4913543/189925872-e29e2009-4a5f-4268-89ce-1055e5d993c7.png)
> 
> Surface and Plain Boundaries = true ![image](https://user-images.githubusercontent.com/4913543/189926178-b463b0f0-16d1-41dc-b53c-36d78d955444.png)
> 
> Point Feature: ![image](https://user-images.githubusercontent.com/4913543/189926365-f736b56f-21f5-439a-9baf-e605d5a9d604.png)
> 
> See commit: [iho-ohi/S-101_Portrayal-Catalogue#40 (comment)](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/40#issuecomment-1245507312)

do you want a test dataset for this? I can make one up fairly quickly if you want to test portrayal. Just send me an email and tell me what you need.... (JP)

**Comment by mikan66** [comment] 2022-09-27 11:15
Reviewing issues for PC 1.0.2, I have this one as closed in the PC issues with colors as follows: 
PrimitiveType.Surface and contextParameters.PlainBoundaries          ----> SimpleLineStyle('dash',0.64,'CHGRD')
The remaining portrayal elements are as defined in EMDSCWTR and DSCWTR51.

**Comment by alvarosanuy** [comment] 2022-09-28 01:19
> @mikan66 - The surfaces (Plain and symbolised) should show the new central symbol DSCWTR51.svg (in CHGRF colour) but the only thing I can see is a similar symbol but in magenta (?). I looked at the *.lua file and the instructions seem to be ok though ....... Can you please double check implementation?

Both Surface features must include a central symbol (see above). This symbol was provided by Leo on the 29/8 (ZIP file included in his comment).

**Comment by mikan66** [comment] 2022-09-28 16:04
> EMAREGR1

I do have a logic error and will open a new issue in PC.  Below is sample with central symbol, but note the viewbox offset, (red dot) which may be by design intent?  
![image](https://user-images.githubusercontent.com/4913543/192829555-6749ed11-be6c-44f8-bd32-7e6ae71c9a0b.png)

Plain Boundaries false: 
![image](https://user-images.githubusercontent.com/4913543/192829969-d1b87703-fab5-4504-8185-08b89c9db782.png)

**Comment by mikan66** [comment] 2022-09-28 16:38
> Both Surface features must include a central symbol

See fix https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/126#issuecomment-1261168397

**Comment by alvarosanuy** [comment] 2022-09-28 23:49
@mikan66  - The central symbol shouldn't have an offset (pivot symbol should be in the center).

**Comment by LeoKuzmin** [comment] 2022-09-29 10:23
I have shifted a pivot point of the DSCWTR51 center symbol consciously. As usual a discoloured water area contains additional information, e.g. water tint.  In this case we will view not overlapped symbol.
![image](https://user-images.githubusercontent.com/106175259/193006939-b0e73dc3-3cd6-4263-8104-9a6a7c758d44.png)

If a pivot point is in the center of DSCWTR51 symbol, the symbol will be overlapped by the INFORM01 symbol. I suppose it is not quite good presentation.
![image](https://user-images.githubusercontent.com/106175259/193006545-a0f53bc5-481e-47a4-abaf-26f102c99283.png)

**Comment by alvarosanuy** [comment] 2022-09-30 01:52
Look, I haven't done a thorough investigation but my initial assessment found that no central symbol has been given an offset just to avoid a potential clashing against the display of the 'highlight date' ('d') or the 'highlight information' ('i') symbology. It is common to see the magenta pointers start from the centre of point features and area central symbols.

There may be a confusion here with the symbols allocated by the CSPs RESARE01 and RESTRN01. The resulting symbols have an offset because many of them may be triggered at the same time or, like in the case of ACHARE, the originating feature itself already has a large central symbol in the centre of the area.

None of this applies to **DiscolouredWater**. Therefore, in my opinion, we need to follow existing practice and put the symbol DSCWTR51.svg in the centre of the Surface with no offset.

**Comment by DavidGrant-NIWC** [comment] 2022-09-30 17:58
Not saying that it should be the case here, but centered area symbols are sometimes offset so that they "disappear" when you zoom out or the area is small. If there is no offset then even tiny areas will always show the centered symbol.

![image](https://user-images.githubusercontent.com/62906211/193328773-74d31826-0019-4702-9bef-e79eb82bec97.png)

![image](https://user-images.githubusercontent.com/62906211/193328830-11a44bee-2238-4eb5-871a-c9b1fda820ae.png)

![image](https://user-images.githubusercontent.com/62906211/193329047-017da3d4-465a-4ebc-bc9a-a4acd829272c.png)

![image](https://user-images.githubusercontent.com/62906211/193329132-1959130b-4a48-4680-8abe-58f0d24fa4fb.png)

**Comment by alvarosanuy** [comment] 2022-10-24 04:29
@LeoKuzmin - Can you please generate and upload a new version of DSCWTR51, **without an offset**? This would be used for PC 1.0.2 but we could make changes if negative feedback is received after the testing phase and before we move to PC 2.0.0.

**Comment by LeoKuzmin** [comment] 2022-10-27 11:07
@alvarosanuy - Please, find the attached zip file with all necessary files for the portrayal of Discoloured Area. The symbol DSCWTR51 and doc files has been modified.
[DiscolouredWater_#61.zip](https://github.com/S-101-Portrayal-subWG/Working-Documents/files/9878701/DiscolouredWater_.61.zip)

**Comment by alvarosanuy** [comment] 2022-10-27 21:35
Implemented in PC 1.0.2

**Closed as completed by alvarosanuy** 2022-10-27 21:35 UTC
Labels: New Portrayal, PC 1.0.2
