### ISSUE TITLE
Default 'text' position when textPlacement is not encoded

### ISSUE THREAD

**Issue by alvarosanuy** [S-101-Portrayal-subWG/Working-Documents#30] opened 2021-05-31 05:12 UTC
**Action item S101PT7 -07** - Refer to paper [S-101PT7_12](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT7/S-101PT7_2021_12_EN_CARIS%20proposal%20to%20amend%20S-101%20TextPlacement%20Attribution%20in%20S-101%20Ed%202_V%202.pdf) submitted by CARIS & CHS

Discuss and make sure 'default' text positions to use by ECDIS when **textPlacement** is not encoded are defined in S-101 PC and/or other documents as required.

**Comment by alvarosanuy** [comment] 2021-05-31 05:40
Is this action about migrating text display instructions contained in the S-52 LUTs (based on S-52 Part I, section 9.1 SHOWTEXT specifications) to the new (proposed) distance & bearing format??
In this case we should:
- replicate existing instructions using new methodology
- identify new/remodeled S-101 features that require text placement instructions and come up with 'default' tvalues.

What else should we discuss here?

**Comment by TDYCARHugh** [comment] 2021-05-31 12:06
The proposed placement by bearing and distance is meant for when text is being placed cartographically using the TextPlacement feature especially when placing text for point features. We can still use the default placement offsets for texts as was used in S-52.  The initial XSLT S-101 portrayal was using the defaults from S-52 and I believe that NIWC converted those into the draft Lua implementation that they are using in the testbed.

**Comment by alvarosanuy** [comment] 2021-06-01 05:35
Sorry for any confusion.
I couldn't attend S101PT7 and therefore I was trying to understand/guess the scope of the Action item that was allocated to this subWG. My first thought followed the same logic than Hugh's and in fact, I'm pretty sure NIWC has already fully (I think) implemented default text locations as per S-52. My conclusion then was that this action could be about implementing a unique methodology to position text (default or driven by TextPlacement). It seems I was wrong ......

Can please somebody that attended the meeting clarify the scope of this action for me? Jeff?

**Comment by DavidGrant-NIWC** [comment] 2021-06-01 14:27
Believe the actions are:
* [ ] Approve proposed portrayal of **TextPlacement**
* [ ] Approve addition of _bearing_ and _distancemm_ attributes to **TextPlacement** feature (assign to DCEG group?).
* [ ] Update FC to reflect change to DCEG (Who has WI? Recommend moving FC development to GitHub).
* [ ] Monitor S-100 WG approval of required change to S-100 Part 9 / S-100 portrayal schema.
* [ ] Update S-101 PC to implement TextPlacement. See [S-101 PC WI](https://github.com/iho-ohi/S-101_Portrayal-Catalogue/issues/3).
* [ ] Create test data containing TextPlacement
* [ ] Verify implementation

**Comment by alvarosanuy** [comment] 2021-06-02 02:32
Below is a copy of the Decisions and Actions listed in the S101PT7 draft minutes (recently circulated for comments):

**S-101PT6-12 – Modify TextPlacement to Support Bearing/Distance [Teledyne CARIS/CA]**
[Docs: Modify TextPlacement to Support Bearing/Distance (Rev1)]
HA presented the proposal to modify the S-101 TextPlacement cartographic feature to implement a bearing and distance methodology for locating text in relation to an associated feature rather than a fixed position and flip bearing methodology. It is suggested that this implementation will simplify text placement, given the confusion that exists over the current methodology, in particular the application of the flipBearing attribute.
The proposal was well received, although there was some **discussion on the possible retention of the flipBearing attribute** that reinforced the confusion in regard to the implementation of this attribute. There was also some discussion on the recommendation to amend the textType attribute value 2 (light characteristic) to make this value more generic, which was agreed requires further discussion within the DCEG Sub-Group.
**It was also stated that a “default” text position in relation to the feature also needs to be specified if the TextPlacement is not created, with agreement that assurance that this specification is included in S-101 is to be discussed within the S-101 DCEG and Portrayal Sub-Groups.**

**Decisions/Actions:**

**Decision**: It was agreed to move forward with the recommendations included in the Paper Modify TextPlacement to Support Bearing/Distance at the S-101PT Sub-Group level. **Discussion to take into account S-101PT7 discussions regarding the attributes flipBearing** and textType; **and ensuring a default text placement specification is included in S-101**.

**Action S-101PT7-07:** Include the Paper Modify TextPlacement to Support Bearing/Distance as a new Issue in the S-101 Documentation and FC GitHub repository (https://github.com/iho-ohi/S-101-Documentation-and-FC) for discussion within the DCEG Sub-Group; and the S-101 Portrayal GitHub repository (https://github.com/iho-ohi/S-101-Portrayal-SubWG) for portrayal implications. (JW/AS)

Based on the content highlighted in bold text, it looks to me that the S101PT expects this subWG to:

- [ ] discuss the introduction of bearing/distance for textPlacement and recommend action
- [ ] discuss the retention of flipBearing even if bearing/distance is approved
- [ ] confirm 'default' text placement specifications (when textPlacement is not created) are included in S-101 (??)

**Comment by TDYCARHugh** [comment] 2021-06-02 12:48
**Re Default text position when TextPlacement not encoded**
The S-52 and initial S-101 portrayal includes text offsets for positioning of text. Those would still be used when there is no TextPlacement feature.  These default text offsets are based on portrayal (screen) coordinates in mm.  When using a course up display the text will stay in the same x,y offset from the feature but the underlying features (e.g. skin of the earth) will effectively rotate under the text. There is no implementation in the existing portrayal to take into consideration what the text may be overwriting (such as a channel).  The addition of TextPlacement in S-101 was meant to allow producers to provide placements of text to reduce clutter and keep text out of channels and such.

**Text Placement by bearing/distance**
My proposal for new attributes on TextPlacement for bearing and distance does not break existing implementations of TextPlacement by geographic position. I would expect the portrayal to use the bearing and distance offset from the geographic position of the TextPlacement feature so if they are not defined the text would be placed at the location of the feature.  I am proposing that for Point features the TextPlacement feature would share the same location and use the bearing and distance to place the text.  The portrayal implementation would create an augmentedRay if bearing the distance are provided and place the text at the end of the Ray. The text would be centred at the endpoint of the ray and always drawn screen up to maintain readability.

**textType attribute**
The textType attribute was intended to let the portrayal know which text is being placed by the TextPlacement feature. The two enum choices are currently 'Feature Name' and 'Light Characteristic'.  But what about radio channels or seabed characteristics.  There was some discussion about including the name of the attribute where the text is coming from but the text string can be assembled from a set of attributes.  We could do a scan of portrayal catalogues and try to make a full list of textTypes.  Looking at it from a general perspective I think it is rare for a feature to have more than two text strings associated with it. My suggestion was to make the enumerations more generic such as 'identifier' and 'characteristics'.  Identifier could be name or some other form of identifier such as a call sign or number.  Characteristics could be light characteristics, seabed info, channel number,...   Looking for input on this.

**flipBearing**
The current implementation of flipBearing is not well defined, understood or simple to implement.  When I proposed just deleting it in favour of bearing and distance there was some push back from some who have used it in some way and feel it is useful.  One example given by SHOM was an implementation that was using the flipBearing as a rotation angle to draw the text at a given bearing angle in order to avoid collisions with other content.   If this is considered useful then the definition of the flipBearing attribute could be made more clear for this purpose.  It is likely there are other implementations or understandings of flipBearing so there may be more cases to consider.

**Keeping text readable**
Some of the discussions on this topic indicated that we may still have some work to do with respect to what should happen if text is being drawn on a line geometry and whether the text is expected to be 'flipped' when the angle of the line at the text placement location would cause the text to draw upside down. The current portrayal documentation does not say much about keeping text readable (screen up) such as is found in paper charts. This should be pursued under a separate issue. Text placed by TextPlacement feature should be using the PortrayalCRS and thus be always screen up.

**Comment by DavidGrant-NIWC** [comment] 2021-06-02 20:10
> **textType attribute**
> [...] Looking for input on this.

Assuming we never need to differentiate between more than two possible strings for a given feature, we could just have _Name_  and _Annotation_. _Name_ indicates the primary label is being positioned, _Annotation_ indicates the light description, safe clearance, valueOfMagVar, etc. is being positioned.

**Comment by alvarosanuy** [comment] 2021-06-11 02:14
The AHO supports the use of **flipBearing** as proposed by SHOM as this is how we also understood it could work. It seems bearing/distance is all about positioning text horizontally at a relative location from the source. **flipBearing** would allow the rotation of the text, similar to what we see in the screenshot below (hopefully it can be implemented so it works in any screen orientation, not just north-up).
![flipBearing_user case](https://user-images.githubusercontent.com/70189016/121620093-0ceddc00-caad-11eb-9b11-d2b224004d9c.png)

Agree that the functional description of this attribute should be reviewed (how it would work in practice on an ECDIS screen) in order to facilitate both, its understanding by data producers and its implementation by OEMs.

**Closed** 2021-11-15 03:38 UTC
Labels: Portrayal Update, Technical - Implementation

**Comment by alvarosanuy** [comment] 2021-11-15 03:40
There are no additional requirements regarding 'default' text placement. Instructions have been successfully migrated from S-52. Refer to Github Issue # 29 for more discussions around **textPlacement**.
